apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prism.fullname" . }}
  labels:
    {{- include "prism.labels" . | nindent 4 }}
data:
  prism.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
