apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prism
  namespace: prism
  labels:
    app.kubernetes.io/name: prism
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: prism
